python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/base  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/base  --plugins "xuleUnit" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f https://www.sec.gov/Archives/edgar/data/831259/000083125921000029/0000831259-21-000029-xbrl.zip --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --logNoRefObjectProperties --logFormat "[%(messageCode)s] %(message)s" --xule-run-only TAXPROP011,TAXPROP012,TAXPROP013,TAXPROP014,TAXPROP015 >> /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/output.txt

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --logNoRefObjectProperties --logFormat "[%(messageCode)s] %(message)s" --xule-run-only UNITFILT001,UNITFILT002,UNITFILT003,UNITFILT004,UNITFILT005,UNITFILT006,UNITFILT007,UNITFILT008,UNITFILT009,UNITFILT010,UNITFILT011 >> /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/output.txt

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --logNoRefObjectProperties --logFormat "[%(messageCode)s] %(message)s" >> /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/output.txt




python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --xule-run-only CFILT123 --logNoRefObjectProperties --logFormat "[%(messageCode)s] %(message)s" >> /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/output.txt

/Applications/Arelle.app/Contents/MacOS/arelleCmdLine --plugins "xule|xule/xulecat" 

/Applications/Arelle.app/Contents/MacOS/arelleCmdLine --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/base  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --xule-max-recurse-depth=2500


/Applications/Arelle.app/Contents/MacOS/arelleCmdLine --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/ut-ruleset.zip --logNoRefObjectProperties --logFormat "[%(messageCode)s] %(message)s" >> /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/output.txt


#xodel
python3.12 ~/arelle/Arelle-master/arellecmdline.py  --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xodel  --plugins 'xule|xodel' --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel|serializer' -f https://www.sec.gov/Archives/edgar/data/831259/000083125921000029/0000831259-21-000029-xbrl.zip --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --logNoRefObjectProperties  --xule-run-only create_base_taxonomy,create_extension_concepts,create_extension_labels,create_presentation_role,create_presentation --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|xodel|serializer' -f https://www.sec.gov/Archives/edgar/data/831259/000083125921000029/0000831259-21-000029-xbrl.zip --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --logNoRefObjectProperties  --xule-run-only create_base_taxonomy,create_extension_concepts,create_extension_labels,create_presentation_role,create_presentation --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output'

-f '/Users/campbellpryde/Downloads/0001109357-23-000067-xbrl.zip'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f '/Users/campbellpryde/Downloads/0001109357-23-000067-xbrl.zip'  -v --xule-time .005 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/unit.xml --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --xule-run-only units_xml --xule-crash


# Create Existing Units Registry
python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel|serializer|transforms/SEC' -f https://www.sec.gov/Archives/edgar/data/831259/000083125921000029/0000831259-21-000029-xbrl.zip  --xule-run  --xule-time .005 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/unit.xml --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --xule-run-only create_base_unit_taxonomy,create_label_roles,create_label_roles_versionDate,create_utr_concepts,create_datatype_unit_concepts,create_alt_iso_concepts,create_scale_concepts,import_currency_taxonomy,create_labels_standard,add_alt_currency_labels,add_datatype_unit_labels,create_magnatude_labels,create_magnatude_documentation,create_domain_header_concepts,create_domain_labels,create_utr_presentation,create_utr_presentation_role,create_magnitude_presentation_role,create_magnitude_presentation,create_currency_presentation_role,create_currency_presentation,create_datatype_presentation_role,create_datatype_presentation,link_unit_to_builtIndatatype,create_dtr_concepts,create_base_ItemType_concepts,create_data_type_labels,create_inbuilt_data_type_labels,link_unit_to_datatype,link_currency_to_datatype,create_operator_arcroles,create_utr_definition_role,link_unit_to_unit,add_reference_qname,add_reference_qname_datatype,add_reference_qname_alt,add_reference_qname_si,add_reference_parts,add_reference_qname_datatypes,add_reference_qname_inbuilt_datatypes,create_label_roles_conversionPresentation,create_currency_entry_point_taxonomy  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel|serializer|transforms/SEC' -f https://www.sec.gov/Archives/edgar/data/831259/000083125921000029/0000831259-21-000029-xbrl.zip  --xule-run  --xule-time .005 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/unit.xml --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xodel-ruleset.zip --xule-run-only test3  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output'



#ReadUnitTest
python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/efmUnitTest/extractDocs  --plugins "xuleUnit" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/efmUnitTests-ruleset.zip --xule-max-recurse-depth=2500


python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xuleUnit|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f /Users/campbellpryde/Downloads/efm-68d-231120/conf/605-instance-syntax/605-01-entity-identifier-scheme/e60501000gd-20111231.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/efmUnitTests-ruleset.zip --logNoRefObjectProperties --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/concept.xml --xule-crash --xule-arg TEST_CASE_ID=e60501000gd

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xuleUnit|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f /Users/campbellpryde/Downloads/efm-68d-231120/conf/605-instance-syntax/605-01-entity-identifier-scheme/e60501001ng-20111231.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/efmUnitTests-ruleset.zip --logNoRefObjectProperties --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/concept.xml --xule-crash --xule-arg TEST_CASE_ID=e60501001ng

#RCreateUnitTest
python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/efmUnitTest/createDocs  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/createUnitTests-ruleset.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel|serializer|xince' -f /Users/campbellpryde/Downloads/efm-68d-231120/conf/605-instance-syntax/605-01-entity-identifier-scheme/e60501000gd-20111231.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/createUnitTests-ruleset.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/conf' --xince-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/e60501000gd.zip' --xince-file-type=xml

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule|xodel|serializer' -f /Users/campbellpryde/Downloads/efm-68d-231120/conf/605-instance-syntax/605-01-entity-identifier-scheme/e60501000gd-20111231.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/createUnitTests-ruleset.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/EFMUnitTests/conf' --xince-file-type=xml --xodel-show-xule-log



python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule/savexuleqnames' --xule-qnames-format json --xule-qnames-dir '/Users/campbellpryde/Documents/GitHub/ferc-renderer/taxonomy/form1/2024/'  -f 'https://eCollection.ferc.gov/taxonomy/form1/2024-04-01/form/form1/form-1_2024-04-01.xsd' --noCertificateCheck

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xule/savexuleqnames' --xule-qnames-format json --xule-qnames-dir '/Users/campbellpryde/Documents/GitHub/xule.dqc/dqc_us_rules/taxonomy/ifrs/2024/'  -f 'https://xbrl.ifrs.org/taxonomy/2024-03-27/full_ifrs_entry_point_2024-03-27.xsd' --noCertificateCheck


python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2024Taxonomy/2023-roll-2024  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2023-2024.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2023Taxonomy/2022  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2023Taxonomy/2021  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2023Taxonomy/2020  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2020.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2023Taxonomy/2019  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --xule-compile /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/roll2023Taxonomy/2018  --plugins "xule" --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2018.zip --xule-max-recurse-depth=2500

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1709164/000170916423000015/hbb-20221231_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='hbb_taxonomy' --xule-arg TICKER='hbb' --xule-arg NEW_CO_NAMESPACE='http://www.hamiltonbeachbrands.com/20231231' --xule-arg OLD_CO_NAMESPACE='http://www.hamiltonbeachbrands.com/20221231' --xule-arg INSTANCE_NAME='hbb-20231231_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/91419/000009141923000072/sjm-20230430_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20240430' --xule-arg PUBLISH_TAXONOMY='sjm_taxonomy' --xule-arg TICKER='sjm' --xule-arg NEW_CO_NAMESPACE='http://smuckers.com/20240430' --xule-arg OLD_CO_NAMESPACE='http://smuckers.com/20230430' --xule-arg INSTANCE_NAME='sjm-20240430_htm'


python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/30554/000175567223000005/ctva-20221231_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='ctva_taxonomy' --xule-arg TICKER='ctva' --xule-arg NEW_CO_NAMESPACE='http://www.corteva.com/20231231' --xule-arg OLD_CO_NAMESPACE='http://www.corteva.com/20221231' --xule-arg INSTANCE_NAME='ctva-20231231_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/72333/000007233323000186/jwn-20231028_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20241028' --xule-arg PUBLISH_TAXONOMY='jwn_taxonomy' --xule-arg TICKER='jwn' --xule-arg NEW_CO_NAMESPACE='http://www.nordstrom.com/20241028' --xule-arg OLD_CO_NAMESPACE='http://www.nordstrom.com/20231028' --xule-arg INSTANCE_NAME='jwn-20231231_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1349706/000121465922014094/i111122510q_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2022.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230930' --xule-arg PUBLISH_TAXONOMY='imhc_taxonomy' --xule-arg TICKER='imhc' --xule-arg NEW_CO_NAMESPACE='http://imhccorp.com/20230930' --xule-arg OLD_CO_NAMESPACE='http://imhccorp.com/20220930' --xule-arg INSTANCE_NAME='imhc-20230930_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1479681/000160706221000537/clnh093021form10q_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230930' --xule-arg PUBLISH_TAXONOMY='clnh_taxonomy' --xule-arg TICKER='clnh' --xule-arg NEW_CO_NAMESPACE='http://clinigence.com/20230930' --xule-arg OLD_CO_NAMESPACE='http://clinigence.com/20210930' --xule-arg INSTANCE_NAME='clnh-20230930_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1543652/000109690622000881/fflo-20211231_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='fflo_taxonomy' --xule-arg TICKER='ffloh' --xule-arg NEW_CO_NAMESPACE='http://freeflowplc.com/20231231' --xule-arg OLD_CO_NAMESPACE='http://freeflowplc.com/20211231' --xule-arg INSTANCE_NAME='fflo-20231231_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1860173/000190359622000919/f10q_privacyvalue_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231031' --xule-arg PUBLISH_TAXONOMY='pcvl_taxonomy' --xule-arg TICKER='pcvl' --xule-arg NEW_CO_NAMESPACE='http://pcvl/20231031' --xule-arg OLD_CO_NAMESPACE='http://pcvl/20221031' --xule-arg INSTANCE_NAME='pcvl-20231031_htm'


python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1057706/000105770622000007/fbp0331202210q_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231031' --xule-arg PUBLISH_TAXONOMY='fbp_taxonomy' --xule-arg TICKER='fbp' --xule-arg NEW_CO_NAMESPACE='http://www.firstbankpr.com/20230331' --xule-arg OLD_CO_NAMESPACE='http://www.firstbankpr.com/20220331' --xule-arg INSTANCE_NAME='fbp-20230331_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/47518/000004751821000084/hrc-20210930_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2021.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230930' --xule-arg PUBLISH_TAXONOMY='hrc_taxonomy' --xule-arg TICKER='hrc' --xule-arg NEW_CO_NAMESPACE='http://hill-rom.com/20230930' --xule-arg OLD_CO_NAMESPACE='http://hill-rom.com/20210930' --xule-arg INSTANCE_NAME='hrc-20230930_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/24741/000156276221000023/glw-20201231x10k_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2020.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='glw_taxonomy' --xule-arg TICKER='glw' --xule-arg NEW_CO_NAMESPACE='http://www.corning.com/20231231' --xule-arg OLD_CO_NAMESPACE='http://www.corning.com/20201231' --xule-arg INSTANCE_NAME='glw-20231231_htm'


python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1353283/000135328319000012/a430201910q_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230430' --xule-arg PUBLISH_TAXONOMY='splk_taxonomy' --xule-arg TICKER='splk' --xule-arg NEW_CO_NAMESPACE='http://www.splunk.com/20230430' --xule-arg OLD_CO_NAMESPACE='http://www.splunk.com/20190430' --xule-arg INSTANCE_NAME='splk-20230430_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1417398/000141739820000042/hi-20200930_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230930' --xule-arg PUBLISH_TAXONOMY='hi_taxonomy' --xule-arg TICKER='hi' --xule-arg NEW_CO_NAMESPACE='http://www.hill.com/20230930' --xule-arg OLD_CO_NAMESPACE='http://www.hillenbrandinc.com/20200930' --xule-arg INSTANCE_NAME='hi-20230930_htm'

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1001082/000155837019006461/dish-20190630x10q_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230630' --xule-arg PUBLISH_TAXONOMY='dish_taxonomy' --xule-arg TICKER='dish' --xule-arg NEW_CO_NAMESPACE='http://www.dishnetwork.com/20230630' --xule-arg OLD_CO_NAMESPACE='http://www.dishnetwork.com/20190630' --xule-arg INSTANCE_NAME='dish-20230630_htm' 

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/13239/000001323920000006/hsc-20191231.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='hsc_taxonomy' --xule-arg TICKER='hsc' --xule-arg NEW_CO_NAMESPACE='http://www.hexion.com/20191231' --xule-arg OLD_CO_NAMESPACE='http://www.hexion.com/20191231' --xule-arg INSTANCE_NAME='hsc-20231231_htm' 

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1390777/000139077720000044/form10-k4q19_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20231231' --xule-arg PUBLISH_TAXONOMY='bk_taxonomy' --xule-arg TICKER='bk' --xule-arg NEW_CO_NAMESPACE='http://www.bnymellon.com/20231231' --xule-arg OLD_CO_NAMESPACE='http://www.bnymellon.com/20191231' --xule-arg INSTANCE_NAME='bk-20231231_htm' 

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1440153/000167343120000036/bkhu-20200430.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2018.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230430' --xule-arg PUBLISH_TAXONOMY='bkhu_taxonomy' --xule-arg TICKER='bkhu' --xule-arg NEW_CO_NAMESPACE='http://BKHU/20230430' --xule-arg OLD_CO_NAMESPACE='http://BKHU/20200430' --xule-arg INSTANCE_NAME='bkhu-20230430_htm' 

python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1304161/000165495419010776/pbsv-20190731.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2019.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20230731' --xule-arg PUBLISH_TAXONOMY='pbsv_taxonomy' --xule-arg TICKER='pbsv' --xule-arg NEW_CO_NAMESPACE='http://pharmabioserv.com/20230731' --xule-arg OLD_CO_NAMESPACE='http://pharmabioserv.com/20190731' --xule-arg INSTANCE_NAME='pbsv-20230731_htm' 


python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins 'xodel' -f https://www.sec.gov/Archives/edgar/data/1308547/000162828024048519/dlb-20240927_htm.xml --xule-run --noCertificateCheck --xule-rule-set /Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/taxRoll2023-2024.zip  --logFile /Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/create.xml  --xodel-location '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/taxRoll/conf' --xince-file-type=xml --xodel-show-xule-log --httpuseragent campbell.pryde@xbrl.us --xule-max-rule-iterations 25000 --xule-arg TAXONOMY_DATE='20241231' --xule-arg PUBLISH_TAXONOMY='dolby_taxonomy' --xule-arg TICKER='dolb' --xule-arg NEW_CO_NAMESPACE='http://www.dolby.com/20241231' --xule-arg OLD_CO_NAMESPACE='http://www.dolby.com/20240927' --xule-arg INSTANCE_NAME='dolby-20230731_htm'