
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/Financials/110-Statement-BalanceSheet.html --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/Financials/110-Statement-BalanceSheet.zip' 

python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-render --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/Financials/110-Statement-BalanceSheet.zip'  -f /Users/campbellpryde/Documents/GitHub/xule/unitTests/instance/xendr/Financials/xbrlus-20181231.htm --xendr-inline '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/xendr/Financials/110-Statement-BalanceSheet.html' --xendr-debug --xendr-show-xule-log


python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/Financials/2023-Statement-BalanceSheet.html --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/Financials/2023-Statement-BalanceSheet.zip' 


python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-render --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/Financials/2023-Statement-BalanceSheet.zip'  -f /Users/campbellpryde/Documents/GitHub/xule/unitTests/instance/xendr/Financials/adbe-20230602-597443.xml --xendr-inline '/Users/campbellpryde/Documents/GitHub/xule/unitTests/output/xendr/Financials/adbe-20230602-597443.html' --xendr-debug --xendr-show-xule-log

python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - 1F - Cover.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - 1F - Cover.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - 1F - Instructions.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - 1F - Instructions.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - 1F - List of Schedules.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - 1F - List of Schedules.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - 3Q - Cover.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - 3Q - Cover.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - Cover.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - Cover.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 000 - Instructions.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 000 - Instructions.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 001 - 1F - Identification.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 001 - 1F - Identification.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 001 - 3Q - Identification.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 001 - 3Q - Identification.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 001 - Identification.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 001 - Identification.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 002 - 1F - Annual Corporate Officer Certification.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 002 - 1F - Annual Corporate Officer Certification.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 002 - 3Q - List of Schedules.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 002 - 3Q - List of Schedules.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 002 - List of Schedules.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 002 - List of Schedules.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 003 - 1F - Comparative Balance Sheet - Assets And Other Debits.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 003 - 1F - Comparative Balance Sheet - Assets And Other Debits.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 003 - 1F - Comparative Balance Sheet - Liabilities and Other Credits.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 003 - 1F - Comparative Balance Sheet - Liabilities and Other Credits.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 004 - 1F - Statement of Income.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 004 - 1F - Statement of Income.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 005 - 1F - Statement of Retained Earnings.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 005 - 1F - Statement of Retained Earnings.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 006 - 1F - Statement of Cash Flows.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 006 - 1F - Statement of Cash Flows.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 007 - 1F - Statement of Accumulated Other Comprehensive Income and Hedging Activities.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 007 - 1F - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 008 - 1F - Notes to Financials.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 008 - 1F - Notes to Financials.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 009 - 1F - Allowances (Accounts 158.1 and 158.2).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 009 - 1F - Allowances (Accounts 158.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 010 - 1F - Other Regulatory Assets.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 010 - 1F - Other Regulatory Assets.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 011 - 1F - Data on Officers and Directors.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 011 - 1F - Data on Officers and Directors.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 012 - 1F - Accumulated Provision for Depreciation and Amortization of Utility Plant.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 012 - 1F - Accumulated Provision for Depreciation and Amortization of Utility Plant.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 013 - 1F - Capital Stock.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 013 - 1F - Capital Stock.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 014 - 1F - Long-Term Debt.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 014 - 1F - Long-Term Debt.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 015 - 1F - Other Regulatory Liabilities (Account 254).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 015 - 1F - Other Regulatory Liabilities (Account 254).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 016 - 1F - Electric Operating Revenues.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 016 - 1F - Electric Operating Revenues.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 017 - 1F - Electric Operations And Maintenance Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 017 - 1F - Electric Operations And Maintenance Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 018 - 1F - Sales for Resale.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 018 - 1F - Sales for Resale.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 019 - 1F - Purchased Power.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 019 - 1F - Purchased Power.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 020 - 1F - Utility Plant Data.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 020 - 1F - Utility Plant Data.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 021 - 1F - Footnote Data.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 021 - 1F - Footnote Data.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 022 - 1F - Purchases and Sales of Ancillary Services.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 022 - 1F - Purchases and Sales of Ancillary Services.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 023 - 1F - Monthly Trans Peak Load.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 023 - 1F - Monthly Trans Peak Load.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 024 - 1F - Transmission Service and Generation Interconnection Study Cost.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 024 - 1F - Transmission Service and Generation Interconnection Study Cost.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 025 - 1F - Amounts Included in ISO RTO Settlement Statments.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 025 - 1F - Amounts Included in ISO RTO Settlement Statments.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 101 - General Information.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 101 - General Information.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 102 - Control Over Respondent.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 102 - Control Over Respondent.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 103 - Corporations Controlled by Respondent.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 103 - Corporations Controlled by Respondent.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 104 - Officers.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 104 - Officers.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 105 - Directors.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 105 - Directors.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 106 - Information on Formula Rates.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 106 - Information on Formula Rates.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 106a - Information on Formula Rates.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 106a - Information on Formula Rates.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 106b - Information on Formula Rates.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 106b - Information on Formula Rates.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 108 - Important Changes.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 108 - Important Changes.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 114 - Statement of Income.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 114 - Statement of Income.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 118 - Statement of Retained Earnings.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 118 - Statement of Retained Earnings.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 120 - Statement of Cash Flows.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 120 - Statement of Cash Flows.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 122 - Notes to Financials.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 122 - Notes to Financials.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 202 - Nuclear Fuel.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 202 - Nuclear Fuel.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 204 - Electric Plant in Service.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 204 - Electric Plant in Service.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 208 - 3Q - ELECTRIC PLANT IN SERVICE AND ACCUMULATED PROVISION FOR DEPRECIATION BY FUNCTION.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 208 - 3Q - ELECTRIC PLANT IN SERVICE AND ACCUMULATED PROVISION FOR DEPRECIATION BY FUNCTION.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 213 - Electric Plant Leased to Others.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 213 - Electric Plant Leased to Others.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 214 - Electric Plant Held for Future Use.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 214 - Electric Plant Held for Future Use.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 216 - Construction Work in Progress - Electric.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 216 - Construction Work in Progress - Electric.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 224 - Investments in Subsidiary Companies.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 224 - Investments in Subsidiary Companies.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 227 - Materials and Supplies.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 227 - Materials and Supplies.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 228a - Allowances (Accounts 158.1 and 158.2).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 228a - Allowances (Accounts 158.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 228b - Allowances (Accounts 158.1 and 158.2).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 228b - Allowances (Accounts 158.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 230a - Extraordinary Property Losses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 230a - Extraordinary Property Losses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 230b - Unrecovered Plant and Regulatory Study Costs.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 230b - Unrecovered Plant and Regulatory Study Costs.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 232 - Other Regulatory Assets.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 232 - Other Regulatory Assets.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 233 - Miscellaneous Deferred Debits (Account 186).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 233 - Miscellaneous Deferred Debits (Account 186).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 234 - Accumulated Deferred Income Taxes.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 234 - Accumulated Deferred Income Taxes.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 250 - Capital Stock.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 250 - Capital Stock.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 253 - Other Paid-In Capital (Accounts 208-211).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 253 - Other Paid-In Capital (Accounts 208-211).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 254b - Capital Stock Expense (Account 214).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 254b - Capital Stock Expense (Account 214).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 256 - Long-Term Debt.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 256 - Long-Term Debt.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 262 - Taxes Accrued, Prepaid and Charged During Year.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 262 - Taxes Accrued, Prepaid and Charged During Year.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 266 - Accumulated Deferred Income Tax Credits.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 266 - Accumulated Deferred Income Tax Credits.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 269 - Other Deferred Credits (Account 253).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 269 - Other Deferred Credits (Account 253).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 272 - Accumulated Deferred Income Taxes-Accelerated Amortization Property.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 272 - Accumulated Deferred Income Taxes-Accelerated Amortization Property.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 276 - ADIT-Other.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 276 - ADIT-Other.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 278 - Other Regulatory Liabilities (Account 254).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 278 - Other Regulatory Liabilities (Account 254).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 300 - Electric Operating Revenues.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 300 - Electric Operating Revenues.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 302 - Regional Transmission Service Revenues.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 302 - Regional Transmission Service Revenues.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 440.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 440.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Commercial.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Commercial.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Industrial.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Industrial.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 444.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 444.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 445.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 445.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 446.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 446.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 448.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 448.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 449.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules 449.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 304 - Sales of Electricity by Rate Schedules.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 310 - Sales for Resale.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 310 - Sales for Resale.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 320 - Electric Operations And Maintenance Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 320 - Electric Operations And Maintenance Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 324 - 3Q - Electric Production, Other Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 324 - 3Q - Electric Production, Other Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 325 - 3Q - Electric Customer Accounts, Service, Sales, Administrative and General Expense.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 325 - 3Q - Electric Customer Accounts, Service, Sales, Administrative and General Expense.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 326 - Purchased Power.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 326 - Purchased Power.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 328 - Transmission of Electricity for Others.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 328 - Transmission of Electricity for Others.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 331 - Transmission of Electricity by ISO RTOs.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 331 - Transmission of Electricity by ISO RTOs.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 332 - Transmission of Electricity by Others.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 332 - Transmission of Electricity by Others.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 335 - Miscellaneous General Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 335 - Miscellaneous General Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 336 - Depreciation and Amortization of Electric Plant.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 336 - Depreciation and Amortization of Electric Plant.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 338 - 3Q - Depreciation, Depletion and Amortization of Electric Plant.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 338 - 3Q - Depreciation, Depletion and Amortization of Electric Plant.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 350 - Regulatory Commission Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 350 - Regulatory Commission Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 352 - Research, Development and Demonstration Activities.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 352 - Research, Development and Demonstration Activities.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 354 - Distribution of Salaries and Wages.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 354 - Distribution of Salaries and Wages.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 356 - Common Utility Plant and Expenses.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 356 - Common Utility Plant and Expenses.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 398 - Purchases and Sales of Ancillary Services.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 398 - Purchases and Sales of Ancillary Services.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 399 - 3Q - Monthly Peaks and Output.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 399 - 3Q - Monthly Peaks and Output.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 400 - Monthly Trans Peak Load.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 400 - Monthly Trans Peak Load.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 401a - Electric Energy Account.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 401a - Electric Energy Account.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 401b - Monthly Peaks and Output.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 401b - Monthly Peaks and Output.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 402 - Steam Electric Generating Plant Statistics.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 402 - Steam Electric Generating Plant Statistics.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 406 - Hydroelectric Generating Plant Statistics.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 406 - Hydroelectric Generating Plant Statistics.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 408 - Pumped Storage Generating Plant Statistics.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 408 - Pumped Storage Generating Plant Statistics.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 410 - Generating Plant Statistics.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 410 - Generating Plant Statistics.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 414 - ENERGY STORAGE OPERATIONS.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 414 - ENERGY STORAGE OPERATIONS.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 419 - ENERGY STORAGE OPERATIONS (Small Plants).html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 419 - ENERGY STORAGE OPERATIONS (Small Plants).zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 422 - Transmission Line Statistics.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 422 - Transmission Line Statistics.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 424 - Transmission Lines Added During Year.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 424 - Transmission Lines Added During Year.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 426 - Substations.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 426 - Substations.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule
python3 ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr|xule' --xendr-compile --xendr-template '/Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/Form1/Form 1 - 429 - Transactions With Associated Affiliated Companies.html' --xendr-template-set '/Users/campbellpryde/Documents/GitHub/xule/unitTests/compiled/xendr/FERC/Form1/Form 1 - 429 - Transactions With Associated Affiliated Companies.zip'  --xendr-global /Users/campbellpryde/Documents/GitHub/xule/unitTests/source/xendr/FERC/render-constants.xule