#!/bin/bash
# Xule Start Script

### BEGIN INIT INFO
# Provides:          xule
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts/stops Xule
# Description:       This script starts the Xule server
#                    
### END INIT INFO

# Author: Marc Ward <marc.ward@xbrl.us>

# *fix valid year checking (recognizes "usgaap" instead of whole year line 84
# *handle error (or prevent from occurring) when trying to stop the server w
#  while it's loading
# *way to handle killing process while filing is running?


PYTHON=/usr/local/bin/python3
XULEDIR=/srv/arelle/arelle/plugin/xule
RULESET=/srv/arelle/xbrlus/pik
LOGFILE_BASE=/var/log/xbrlus_custom/arelle/arelle
CPUS=2

TAXONOMIES=( "usgaap-2013" "usgaap-2014" "usgaap-2015" "usgaap-2016" )
TAXONOMIES_PORTS=(8084 8085 8086 8087)
TAXONOMIES_THREADS=(3 2 3 3)

IP=$(ifconfig eth0 | awk -F"[: ]+" '/inet addr:/ {print $4}')
YEAR=$2


# Finds index of passed value in $TAXONOMIES array
get_index() {
        value=$1
        for i in "${!TAXONOMIES[@]}"; do
           if [[ "${TAXONOMIES[$i]}" = "${value}" ]]; then
               echo "${i}";
           fi
        done
}



start() {
	declare -a taxonomy_year 
    if [ "$YEAR" != "" ];then
    	if [[ "${TAXONOMIES[@]}" == *"$YEAR"* ]];then
    		taxonomy_year[0]=$YEAR
    	else
    		echo "Xule Server for $YEAR isn't active. Valid taxonomies are: $TAXONOMIES"
    		exit
    	fi
    else
    	taxonomy_year=("${TAXONOMIES[@]}")
    fi

    cd $XULEDIR
    for taxonomy in "${taxonomy_year[@]}"; do
		index=$(get_index "$taxonomy")
    	pid=$(ps -ef |grep $PYTHON | grep $taxonomy | head -n 1)
    	if [ "$pid" != "" ];then
    		echo "Xule for $taxonomy is already running"
    		continue
    	fi
    	$PYTHON XuleServer.py --xule-server $IP:${TAXONOMIES_PORTS[$index]}:cherrypy \
    		--xule-rule-set $RULESET/$taxonomy \
    		--xule-run --xule-multi            \
    		--xule-cpu $CPUS --xule-numthreads ${TAXONOMIES_THREADS[$index]} \
    		--plugins 'xule|transforms/SEC.py' \
    		>> ${LOGFILE_BASE}_${taxonomy}.log 2>&1 &
#    		> >(tee -a ${LOGFILE_BASE}_${taxonomy}.log)  \
#    		2> >(tee -a ${LOGFILE_BASE}_${taxonomy}.log >&2) &
    	echo "Xule $taxonomy Server started. Will be loaded in about 3 minutes"
    done
}
 
stop() {
	declare -a taxonomy_year 
    if [ "$YEAR" != "" ];then
    	if [[ "${TAXONOMIES[@]}" == *"$YEAR"* ]];then
    		taxonomy_year[0]=$YEAR
    	else
    		echo "Xule Server for $YEAR isn't active. Valid taxonomies are: ${TAXONOMIES[@]}"
    		exit
    	fi
    else
    	taxonomy_year=(${TAXONOMIES[@]})
    fi

	for taxonomy in "${taxonomy_year[@]}";do
		pid=$(ps -ef |grep $PYTHON | grep $taxonomy | awk '{ print $2 }' | head -n 1)
		#echo "found pid: $pid"
    	#echo "ps -ef |grep $PYTHON | grep $taxonomy | awk '{ print $2 }' | head -n 1"
    	if [ "$pid" == "" ];then
    		echo "Xule Server: $taxonomy not running"
    	else
    	    #echo "about to kill: $pid"
    	    while [ "$pid" != "" ];do
    	    	echo Attempting to kill $taxonomy
    	    	kill $pid
	    		sleep 10
				pid=$(ps -ef |grep $PYTHON | grep $taxonomy | awk '{ print $2 }' | head -n 1)
	    	done 
    		echo "Xule $taxonomy Server killed."
    	fi
    done
}

status() {
    valid=""
	for taxonomy in "${TAXONOMIES[@]}"; do
		if [ $(ps -ef |grep "$PYTHON" | grep "$taxonomy" | wc -l) -gt 0 ]; then
			valid="$valid $taxonomy"
		fi
	done

	if [ "$valid" != "" ];then
		echo "Active Xule Servers: $valid"
	else
		echo "No Xule Servers active"
	fi


}


case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  status)
  	status
  	;;
  *)
    echo "Usage: /etc/init.d/xule {start|stop|restart}"
    exit 1
esac

exit 0